header_include_path: navsat_converter/navsat_converter.hpp
namespace: navsat_converter
node_class_name: NavSatConverter

params:
  conv.gps.fix_topics:
    type: string_array
    default_value:
      - ""
    description: "NavSatFix topics list."
    constraints: "Must be a list of valid topics name. Put a empty string to disable the conversion."
    read_only: true
    validator: validate_conv_gps_fix_topics

  conv.xyz.odometry_topics:
    type: string_array
    default_value: 
      - ""
    description: "Odometry topics list."
    constraints: "Must be a list of valid topics name. Put a empty string to disable the conversion."
    read_only: true
    validator: validate_conv_xyz_odometry_topics

  conv.xyz.point_topics:
    type: string_array
    default_value:
      - ""
    description: "PointStamped topics list."
    constraints: "Must be a list of valid topics name. Put a empty string to disable the conversion."
    read_only: true
    validator: validate_conv_xyz_point_topics

  conv.xyz.pose_topics:
    type: string_array
    default_value:
      - ""
    description: "PoseStamped topics list."
    constraints: "Must be a list of valid topics name. Put a empty string to disable the conversion."
    read_only: true
    validator: validate_conv_xyz_pose_topics

  conv.xyz.posecov_topics:
    type: string_array
    default_value:
      - ""
    description: "PoseWithCovarianceStamped topics list."
    constraints: "Must be a list of valid topics name. Put a empty string to disable the conversion."
    read_only: true
    validator: validate_conv_xyz_posecov_topics

  earth.frame:
    type: string
    default_value: earth
    description: "Earth frame id."
    constraints: "Must be a valid frame id."
    read_only: true
    var_name: earth_frame_

  earth.gps.lat:
    type: double
    default_value: 0.0
    min_value: -90.0
    max_value: 90.0
    step: 0.0
    description: "Earth frame latitude (North positive)."
    constraints: "Must be a valid real value."
    read_only: true
    var_name: earth_gps_lat_

  earth.gps.lon:
    type: double
    default_value: 0.0
    min_value: -180.0
    max_value: 180.0
    step: 0.0
    description: "Earth frame latitude (East positive)."
    constraints: "Must be a valid real value."
    read_only: true
    var_name: earth_gps_lon_

  earth.gps.alt:
    type: double
    default_value: 0.0
    min_value: -1000000.0
    max_value: 1000000.0
    step: 0.0
    description: "Earth frame altitude (Up positive)."
    constraints: "Must be a valid real value."
    read_only: true
    var_name: earth_gps_alt_

  earth.topic_stream:
    type: bool
    default_value: false
    description: "Enable a NavSatFix to stream Earth frame coordinate updates."
    constraints: "Should be off."
    read_only: false
    var_name: earth_topic_stream_

  target.frame:
    type: string
    default_value: map
    description: "GPS coordinate are converted in the cartesian target frame id."
    constraints: "Must be a valid frame id."
    read_only: true
    var_name: target_frame_

  tf.ignore_stamp:
    type: bool
    default_value: false
    description: "Ignore requested timestamp in TF2 lookup operations"
    constraints: "Should be off."
    read_only: false
    var_name: tf_ignore_stamp_

  tf.timeout_ms:
    type: integer
    default_value: 100
    min_value: 0
    max_value: 60000
    step: 1
    description: "TF2 lookup timeout [ms]."
    constraints: "Must be commensurate to the maximum length of the operation."
    read_only: false
    var_name: tf_timeout_ms_