header_include_path: navsat_converter/navsat_converter.hpp
namespace: navsat_converter
node_class_name: NavSatConverter

params:
  conv_gps_fix_topics:
    type: string_array
    default_value:
      - /fix
    description: "NavSatFix topics list."
    constraints: "Must be a list of valid topics name."
    read_only: true
    var_name: conv_gps_fix_topics_

  conv_xyz_odometry_topics:
    type: string_array
    default_value: 
      - /odometry
    description: "Odometry topics list."
    constraints: "Must be a list of valid topics name."
    read_only: true
    var_name: conv_xyz_odometry_topics_

  conv_xyz_point_topics:
    type: string_array
    default_value:
      - /point
    description: "PointStamped topics list."
    constraints: "Must be a list of valid topics name."
    read_only: true
    var_name: conv_xyz_point_topics_

  conv_xyz_pose_topics:
    type: string_array
    default_value:
      - /pose
    description: "PoseStamped topics list."
    constraints: "Must be a list of valid topics name."
    read_only: true
    var_name: conv_xyz_pose_topics_

  conv_xyz_posecov_topics:
    type: string_array
    default_value:
      - /pose_cov
    description: "PoseWithCovarianceStamped topics list."
    constraints: "Must be a list of valid topics name."
    read_only: true
    var_name: conv_xyz_posecov_topics_

  earth_frame:
    type: string
    default_value: earth
    description: "Earth frame id."
    constraints: "Must be a valid frame id."
    read_only: true
    var_name: earth_frame_

  earth_gps_lat:
    type: double
    default_value: 0.0
    min_value: -90.0
    max_value: 90.0
    step: 0.0
    description: "Earth frame latitude (North positive)."
    constraints: "Must be a valid real value."
    read_only: true
    var_name: earth_gps_lat_

  earth_gps_lon:
    type: double
    default_value: 0.0
    min_value: -180.0
    max_value: 180.0
    step: 0.0
    description: "Earth frame latitude (East positive)."
    constraints: "Must be a valid real value."
    read_only: true
    var_name: earth_gps_lon_

  earth_gps_alt:
    type: double
    default_value: 0.0
    min_value: -1000000.0
    max_value: 1000000.0
    step: 0.0
    description: "Earth frame altitude (Up positive)."
    constraints: "Must be a valid real value."
    read_only: true
    var_name: earth_gps_alt_

  target_frame:
    type: string
    default_value: map
    description: "GPS coordinate are converted in the cartesian target frame id."
    constraints: "Must be a valid frame id."
    read_only: true
    var_name: target_frame_

  tf_ignore_stamp:
    type: bool
    default_value: false
    description: "Ignore requested timestamp in TF2 lookup operations"
    constraints: "Should be off."
    read_only: false
    var_name: tf_ignore_stamp_

  tf_timeout_ms:
    type: integer
    default_value: 100
    min_value: 0
    max_value: 60000
    step: 1
    description: "TF2 lookup timeout [ms]."
    constraints: "Must be commensurate to the maximum length of the operation."
    read_only: false
    var_name: tf_timeout_ms_